[profile.default]
emv_version = "paris"
src = "src"
out = "out"
script = "script"
libs = [
    "node_modules",
    "lib",
]
fs_permissions = [
    { access = "read", path = "out-optimized" },
    { access = "read-write", path = "gas_calculations" },
    { access = "read", path = "./zkout/ERC1967Proxy.sol/ERC1967Proxy.json" },
]
allow_paths = [
    "*",
    "/",
]
ignored_warnings_from = [
    "node_modules",
    "node_modules/@rhinestone/modulekit/src/**/*.sol",
    "lib",
]

#libraries = ["{PROJECT_ROOT}/lib/ether-email-auth/packages/contracts/src/libraries/DecimalUtils.sol:DecimalUtils:0x91cc0f0a227b8dd56794f9391e8af48b40420a0b", "{PROJECT_ROOT}/lib/ether-email-auth/packages/contracts/src/libraries/SubjectUtils.sol:SubjectUtils:0x981e3df952358a57753c7b85de7949da4abcf54a"]
solc = "0.8.26"

[rpc_endpoints]
sepolia = "${BASE_SEPOLIA_RPC_URL}"

# [etherscan]
# sepolia = { key = "${BASE_SCAN_API_KEY}" }

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 100
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
ignore = [
    "./src/libraries/L2ContractHelper.sol",
]

[profile.default.zksync]
zksolc = "1.5.0"